listener 1883
allow_anonymous true

persistence false

log_dest stdout
log_type all
connection_messages true
log_timestamp true

connection broker2-to-broker1
address mqtt-broker:1883
topic iot/# out 0
notifications false
restart_timeout 5
