services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./log:/mosquitto/log
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.10

  mqtt-broker-2:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker-2
    restart: unless-stopped
    volumes:
      - ./config-broker-2/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.11

  mqtt-broker-auth:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker-auth
    restart: unless-stopped
    volumes:
      - ./config-auth/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./config-auth/passwd:/mosquitto/config/passwd:ro
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.12

  iot-client-1:
    image: gi-hsp/iot-client:1.1
    container_name: iot-client-1
    restart: unless-stopped
    environment:
      CLIENT_ID: iot-client-1
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      PUBLISH_INTERVAL: 5
    depends_on:
      - mqtt-broker
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.20

  iot-client-2:
    image: gi-hsp/iot-client:1.1
    container_name: iot-client-2
    restart: unless-stopped
    environment:
      CLIENT_ID: iot-client-2
      MQTT_BROKER: mqtt-broker-2
      MQTT_PORT: 1883
      PUBLISH_INTERVAL: 7
    depends_on:
      - mqtt-broker-2
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.21

  iot-subscriber-1:
    image: gi-hsp/iot-client:1.1
    container_name: iot-subscriber-1
    restart: unless-stopped
    environment:
      CLIENT_ID: iot-subscriber-1
      CLIENT_ROLE: subscriber
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      SUBSCRIBE_TOPIC: iot/#
      PUBLISH_INTERVAL: 1
    depends_on:
      - mqtt-broker
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.30


  hsp-attacker:
    image: gi-hsp/hsp-attacker:0.1
    container_name: hsp-attacker
    restart: unless-stopped
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.40


  hsp-attacker-expanded:
    image: gi-hsp/hsp-attacker-expanded:1.0
    container_name: hsp-attacker-expanded
    restart: unless-stopped
    volumes:
      - ../../hsp/expanded/attacks:/attack:ro
    networks:
      gi-hsp-net:
        ipv4_address: 172.30.0.41


networks:
  gi-hsp-net:
    external: true
